-- Cleanup since last build
DROP DATABASE IF EXISTS drr;
DROP ROLE IF EXISTS drr_user;

CREATE ROLE drr_user WITH LOGIN CREATEDB SUPERUSER ENCRYPTED PASSWORD 'pass';
CREATE DATABASE drr;

ALTER ROLE drr_user NOSUPERUSER;
